### ISSUE TITLE
Where is [[PLAN]] for generation?

### ISSUE THREAD

**Issue by SparkJiao** [Aiden0526/SymbCoT#2]
Hi, Jundong,

Appreciate your contribution to the community very much!

During checking your prompt, I didn't find where to fill the generated plan in your prompts:

For example, in AR-LSAT, the code [here](https://github.com/Aiden0526/SymbCoT/blob/main/symbcot.py#L62-L67) requires filling the generated plan into ``[[PLAN]]``, however, I didn't find the slot in your [prompt](https://github.com/Aiden0526/SymbCoT/blob/main/prompts/AR-LSAT/solver.txt) (I only find ``[[CONTEXT]]``).

Also, I think the in-context examples in `solver.txt` also do not include the plan part.

Could you help with a check if it is missing?

Thank you very much!

Best,
Fangkai

**Comment by Aiden0526** [comment]
Hi Fangkai,

Thank you for raising the issue. I have already fixed the typo and it should work properly now.

**Comment by SparkJiao** [comment]
Hi, thank you for your help very much!

I have checked the updated prompt, however, I found that there is still no [[PLAN]] in the in-context examples part, where the ``context`` part directly follows the instruction. Is this as expected?

**Comment by Aiden0526** [comment]
Hi Fang Kai,

Yes it is expected. In the in-context examples, there is no [[PLAN]] as it would be sufficient to guide the model on solving the problem. The plan will be appended when the problem is being solved.
